### ISSUE TITLE
Images aren't loading at all

### ISSUE THREAD

**Issue by guilsa** [nathanWilson81/reason-image-grid#5]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/6107640/74097185-14b6fe00-4abe-11ea-93cc-3674e244f168.png">

**Comment by nwilson-li** [comment]
The api that the app hits returns placeholder images. The thumbnail of those placeholders are just 600x600 images with a color. If you use the dev tools and grab the src from those images and place them in a tab you'll see that the image loading on the screen is the image provided by the api
